name: fast_store
description: "Fast Store is a API Public App."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
    #State Management Bloc and Modular
  flutter_modular: ^6.4.1
  flutter_bloc: ^9.1.1

  #Network
  dio: ^5.0.0

  #Local DB
  hive: ^2.0.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  #Icons
  cupertino_icons: ^1.0.8
  awesome_snackbar_content: ^0.1.8
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  #
flutter:
  uses-material-design: true
  assets:
    - assets/images/
